version: '3.8'
services:
  frontend:
    build: ./new-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DATABASE_URL=postgres://user:password@db:5432/lavamanagerdb
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lavamanagerdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Opzionale: puoi aggiungere il montaggio per lo script di inizializzazione
    # volumes:
    #   - ./db-init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
